name: 'Google Drive tools'
description: 'Google Drive tools'
inputs:
  parent_id:
    description: 'The ID of the parent folders in remote'
    required: true
    default: ''
  dest_file_name:
    description: 'The name of the file in remote'
    required: true
    default: ''
  src_file_name:
    description: 'The name(path) of the file in local filesystem'
    required: true
    default: ''
outputs:
  file_id:
    description: 'The ID of the file that is sended into Google Drive'
runs:
  using: 'node16'
  main: 'dist/index.js'
