name: 'Google Drive tools'
description: 'Google Drive tools'
inputs:
  parent_id:
    description: 'id of folder on Google Drive'
    required: true
    default: ''
  dest_file_name:
    description: 'file name in Google Drive'
    required: true
    default: ''
  src_file_name:
    description: 'file name in local filesystem'
    required: true
    default: ''
outputs:
  file_id:
    description: 'id of file that is sended into Google Drive'
runs:
  using: 'node16'
  main: 'dist/index.js'
