name: Test action code
on:
  push:
    branches:
      - '**'
      #- '!main'
    tags:
      - '!v*'

jobs:
  test-modules:
    runs-on: ubuntu-latest
    name: Test modules
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-push-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-push-${{ env.cache-name }}-
            ${{ runner.os }}-push-

      - name: Install modules
        run: npm ci

      - name: Run tests
        run: npm run test:build

  test-main:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    name: Test main
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Send file(normal end)
        id: send
        uses: ./
        with:
          parent_id: ${{ secrets.PARENT_ID }}
          dest_file_name: gdrive-act-send-test-readme.md
          src_file_name: README.md

      - name: Check file_id
        run: test -n "${FILE_ID}"
        env:
          FILE_ID: ${{ steps.send.outputs.file_id }}

      - name: Send file(with mime type)
        id: send_with_mime
        uses: ./
        with:
          parent_id: ${{ secrets.PARENT_ID }}
          dest_file_name: gdrive-act-send-test-readme.doc
          src_file_name: README.md
          dest_mime_type: application/vnd.google-apps.document
          src_mime_type: text/markdown

      # mimeType ありで upload されている場合、
      # 上書きするには local 側の mimeType の指定がなければエラーになる(はず)
      - name: Send file(with mime type 2)
        id: send_with_mime2
        uses: ./
        with:
          parent_id: ${{ secrets.PARENT_ID }}
          dest_file_name: gdrive-act-send-test-readme.doc
          src_file_name: README.md
          dest_mime_type: application/vnd.google-apps.document
          src_mime_type: text/markdown

      # fileId でリモートのファイルを特定する
      - name: Send file(with file id)
        id: send_with_file_id
        uses: ./
        with:
          file_id: ${{ steps.send.outputs.file_id }}
          src_file_name: README.md

      - name: Send file(src is not exist)
        id: send_failed
        continue-on-error: true
        uses: ./
        with:
          parent_id: ${{ secrets.PARENT_ID }}
          dest_file_name: gdrive-act-send-test-readme.md
          src_file_name: README_test.md

      - name: Check failure
        run: test "${FAILURE}" = "failure"
        env:
          FAILURE: ${{ steps.send_failed.outcome }}
